defmodule TheBandWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :the_band

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_the_band_key",
    signing_salt: "F6+jpxXU",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :the_band,
    gzip: not code_reloading?,
    only: TheBandWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :the_band
  end

  plug Plug.RequestId

  # FR-029 — correlação em TODA requisição.
  #
  # Fica no endpoint, e não num pipeline do roteador, porque pipeline só se aplica às rotas
  # que o declaram: uma rota nova esquecida ficaria sem correlação, e é justamente na rota
  # esquecida que o diagnóstico faz falta.
  #
  # Vem antes de `Plug.Telemetry` para que os eventos de requisição já encontrem a
  # correlação nos metadados do Logger. Depois de `Plug.RequestId` porque o identificador de
  # requisição do Plug é independente e ambos coexistem nos metadados.
  plug TheBandWeb.Plugs.CorrelationId

  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug TheBandWeb.Router
end
