import Config

# Configure your database
#
# Credenciais de desenvolvimento local, iguais aos padrões do `compose.yaml`. Não são
# segredo: o banco escuta apenas em loopback e não contém dado real. Em produção,
# `config/runtime.exs` exige `DATABASE_URL` do ambiente e não aceita padrão (FR-007).
config :the_band, TheBand.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: 5432,
  database: "the_band_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :the_band, TheBandWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # NÃO é segredo, e é assim de propósito.
  #
  # O gerador do Phoenix escreve aqui uma string aleatória de 64 caracteres. Num repositório
  # público isso é indistinguível de uma credencial vazada: scanner de segredo sinaliza, e
  # quem revisa perde tempo confirmando que é inerte. Substituída por um valor legível que
  # anuncia o que é.
  #
  # Só assina cookie de desenvolvimento em loopback. Produção exige `SECRET_KEY_BASE` do
  # ambiente e não aceita padrão — ver `config/runtime.exs` e FR-007.
  secret_key_base: "dev-only-signing-salt-not-a-secret-do-not-use-outside-localhost-01",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:the_band, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:the_band, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :the_band, dev_routes: true

# Do not include metadata nor timestamps in development logs
# O gerador escreve aqui `format: "[$level] $message\n"`, sem `$metadata`, para manter a saída
# de desenvolvimento curta. O efeito colateral é que a correlação nunca aparece nas linhas de
# log em desenvolvimento — e correlação existe para diagnosticar, sendo desenvolvimento onde
# mais se diagnostica.
#
# Encontrado rodando a aplicação, não pelos portões: o cabeçalho de resposta continha a
# correlação e `TheBand.Telemetry.Handler` a imprimia, mas as linhas de requisição do Phoenix
# a descartavam na formatação.
#
# `$time` fica de fora aqui de propósito: em desenvolvimento o horário é ruído, e a correlação
# não.
config :logger, :default_formatter,
  format: "[$level] $metadata$message\n",
  metadata: [:request_id, :correlation_id, :tenant_id]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
